[build]
builder = "nixpacks"
buildCommand = "git lfs install && git lfs pull && npm install && npm run build --workspace client"

[deploy]
startCommand = "npm run start --workspace server"
healthcheckPath = "/api/health"
healthcheckTimeout = 30

[variables]
NODE_ENV = "production"
